# Generated by Django 6.0.7 on 2026-07-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': [models.OrderBy(models.F('last_commit'), descending=True, nulls_last=True), 'name']},
        ),
        migrations.AddField(
            model_name='project',
            name='last_commit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
